name: design_code_app

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  flutter:
    sdk: flutter
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter_app_name:
  name: "DesignCodeApp"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/illustrations/
    - assets/icons/
    - assets/badges/
    - assets/certificates/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 800
